### ISSUE TITLE
Input not recognizing?

### ISSUE THREAD

**Issue by jae1379** [bayangan1991/PYXInput#12]
This might be a silly question.

pyxinput.test_virtual() works fine and I see the controlled being plugged in and disconnecting.

What command is the plug in controller 1 command? 

When i just copy and paste 
```
`import pyxinput

MyVirtual = pyxinput.vController()

MyRead = pyxinput.rController(1) # For Controller 1

MyVirtual.set_value('BtnA', 1)
MyVirtual.set_value('AxisLx', -0.5)

print(MyRead.gamepad)
print(MyRead.buttons)`
```
I hear plugging in sound but I no game controller is being recognized on the driver side. Thank you very much in advance

**Comment by bayangan1991** [comment]
Hi @jae1379,
the `pyxinput.vController()` is what "plugs in" the controller.

This block of code will only have the controller plugged in for less than a second as there is no long blocking call.

You may want to put a loop, or a long `time.sleep()` command at the end if you are trying to figure out the library.

**Comment by jae1379** [comment]
Thank you very much! @bayangan1991
