### ISSUE TITLE
Broken DLL Dependancies

### ISSUE THREAD

**Issue by bayangan1991** [bayangan1991/PYXInput#2]
Because I compiled [vXboxInterface.dll](/bayangan1991/PYXInput/blob/master/pyxinput/vXboxInterface-x64/vXboxInterface.dll) in debug mode all the dependancies are screwed up. I will fix this at earliest convenience.

**Comment by Flandan** [comment]
This seems to be working fine now, both the buttons and joystick output are working. I can't test the capture as I don't have a controller.
