### ISSUE TITLE
No way to set specific Dpad button off

### ISSUE THREAD

**Issue by GoelBiju** [bayangan1991/PYXInput#9]
I only noticed this issue whilst trying to release a Dpad button. If I press DPAD_UP using:

```python
MyVirtual.set_value('Dpad', 1)
```

Then I can only set it to off using:

```python
MyVirtual.set_value('Dpad', 0)
```

Is there a way in which I can turn off a particular button i.e. keep DPAD_UP on but turn off DPAD_DOWN?

**Comment by bayangan1991** [comment]
Hi @GoelBiju ,

The `Dpad` variable takes a single integer as an argument. Which buttons are pressed is determined by the sum of buttons pressed.

For example:
- To have Up and Down pressed at the same time you would send the sum of `DPAD_UP + DPAD_DOWN == 1 + 2 == 3`.
- To only have Up pressed you would only send `DPAD_UP == 1`.
- For Down and Right `DPAD_DOWN + DPAD_RIGHT == 2 + 8 == 10`

**Comment by GoelBiju** [comment]
That's great, thanks for notifying me @bayangan1991
